{{- if .Values.chartPalonso.phpmyadmin.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-phpmyadmin-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_DATABASE_PASSWORD: "{{ .Values.chartPalonso.resources.mysql.credentials.passwordDb }}"
  DB_ROOT_PASSWORD: "{{ .Values.chartPalonso.resources.mysql.credentials.passwordRoot }}"
{{- end }}

