apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
