apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-laravel-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: laravel
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
