{{- if .Values.chartPalonso.phpmyadmin.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-phpmyadmin-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: phpmyadmin
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
{{- end }}
